### PR TITLE
Catch uncaught exceptions from Empatica

### LINKED ISSUE #7: App crashes on com.empatica.empalink.ConfigurationProfileException
Starting the Android app using `org.radarcns:radar-android-empatica:0.1-alpha.3` without internet connection raises 

```
01-01 00:08:04.044 3859-4152/org.radarcns.detail E/EMPA_C: Loaded
01-01 00:08:07.865 3859-4273/org.radarcns.detail E/DeviceLabelHandler: Error downloading label file
01-01 00:08:08.117 3859-3859/org.radarcns.detail E/AndroidRuntime: FATAL EXCEPTION: main
Process: org.radarcns.detail, PID: 3859
com.empatica.empalink.ConfigurationProfileException: Login failed and you don't have a valid local configuration profile
at com.empatica.empalink.EmpaDeviceManager.b(EmpaDeviceManager.java:843)
at com.empatica.empalink.EmpaDeviceManager.a(EmpaDeviceManager.java:67)
at com.empatica.empalink.EmpaDeviceManager$b.a(EmpaDeviceManager.java:1005)
at com.empatica.empalink.EmpaDeviceManager$b.onPostExecute(EmpaDeviceManager.java:978)
at android.os.AsyncTask.finish(AsyncTask.java:651)
at android.os.AsyncTask.-wrap1(AsyncTask.java)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

The Android app then crashes without recovering.

### PR DESCRIPTION
**Pull request by blootsvoets**
Catch exceptions from Empatica gracefully. @fnobilia @sboettcher could either of you confirm that this fixes #7?

### CODE REVIEW

**Comment by sboettcher** [comment]
I still get the crash. Looking at the log a bit closer, it looks like it actually passes where I thought the exception would occur...

```
08-29 17:21:32.564 2945-2994/org.radarcns.android.android I/E4DeviceManager: Authenticating EmpaDeviceManager
08-29 17:21:32.567 2945-2994/org.radarcns.android.android I/E4DeviceManager: Authenticated EmpaDeviceManager
...
08-29 17:21:40.234 2945-2999/org.radarcns.android.android E/DeviceLabelHandler: Error downloading label file
08-29 17:21:40.259 2945-2945/org.radarcns.android.android D/AndroidRuntime: Shutting down VM
08-29 17:21:40.260 2945-2945/org.radarcns.android.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: org.radarcns.android.android, PID: 2945
                                                                            com.empatica.empalink.ConfigurationProfileException: Login failed and you don't have a valid local configuration profile
                                                                                at com.empatica.empalink.EmpaDeviceManager.b(EmpaDeviceManager.java:843)
                                                                                at com.empatica.empalink.EmpaDeviceManager.a(EmpaDeviceManager.java:67)
                                                                                at com.empatica.empalink.EmpaDeviceManager$b.a(EmpaDeviceManager.java:1005)
                                                                                at com.empatica.empalink.EmpaDeviceManager$b.onPostExecute(EmpaDeviceManager.java:978)
                                                                                at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                                at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                                at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-29 17:21:40.262 1060-1670/? W/ActivityManager:   Force finishing activity org.radarcns.android.android/org.radarcns.DetailMainActivity
```
edit: unless [authenticateWithAPIKey()](https://github.com/RADAR-CNS/RADAR-Android-Empatica/blob/checked_exceptions/src/main/java/org/radarcns/empatica/E4DeviceManager.java#L110) is a non-blocking call?

**Comment by blootsvoets** [comment]
After every measure taken, it looks like Empatica is still using the main looper to execute... I'll try to see if I can pass a modified Context again which uses the current `HanderThread` looper as the main looper.

**Comment by blootsvoets** [comment]
Indeed the authenticate is asynchronous, using an `AsyncTask` on the main looper.

**Comment by blootsvoets** [comment]
I've updated the code to catch exceptions in the main thread. Does that solve your issue @sboettcher?

**Comment by sboettcher** [comment]
The exception is caught but the app still exits.

Here is a full log (I disabled all services but `.application.ApplicationServiceProvider .phone.PhoneSensorProvider .empatica.E4ServiceProvider`):
<details>
<summary>Log</summary>
<code><pre>
09-04 11:29:37.088 13353-13353/org.radarcns.android.android I/System.out: debugger has settled (1410)
09-04 11:29:37.324 1060-1078/? W/AppOps: Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
09-04 11:29:37.375 13353-13353/org.radarcns.android.android D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
09-04 11:29:37.395 13353-13353/org.radarcns.android.android W/InstanceID/Rpc: Failed to resolve IID implementation package, falling back
09-04 11:29:37.397 13353-13353/org.radarcns.android.android W/InstanceID/Rpc: Google Play services is missing, unable to get tokens
09-04 11:29:37.398 13353-13353/org.radarcns.android.android D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
09-04 11:29:37.473 13353-13353/org.radarcns.android.android I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzauh$zzg>
09-04 11:29:37.474 13353-13353/org.radarcns.android.android I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzauh$zzg>
......
09-04 11:29:37.538 13353-13353/org.radarcns.android.android I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzaug$zzb>
09-04 11:29:37.538 13353-13353/org.radarcns.android.android I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzaug$zzb>
09-04 11:29:37.554 13353-13353/org.radarcns.android.android E/FirebaseApp: Firebase API initialization failure.
                                                                           java.lang.reflect.InvocationTargetException
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.google.firebase.FirebaseApp.zza(Unknown Source)
                                                                               at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                               at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                               at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                               at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
                                                                               at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)
                                                                               at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
                                                                               at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                                               at android.app.ActivityThread.installProvider(ActivityThread.java:5153)
                                                                               at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748)
                                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688)
                                                                               at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                            Caused by: java.lang.NoSuchMethodError: No static method zzyv()Lcom/google/android/gms/common/util/zze; in class Lcom/google/android/gms/common/util/zzh; or its super classes (declaration of 'com.google.android.gms.common.util.zzh' appears in /data/app/org.radarcns.android.android-1/base.apk:classes36.dex)
                                                                               at com.google.android.gms.internal.zzatt.zzn(Unknown Source)
                                                                               at com.google.android.gms.internal.zzatp.<init>(Unknown Source)
                                                                               at com.google.android.gms.internal.zzatt.zzLP(Unknown Source)
                                                                               at com.google.android.gms.internal.zzatp.zzbu(Unknown Source)
                                                                               at com.google.android.gms.measurement.AppMeasurement.getInstance(Unknown Source)
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at com.google.firebase.FirebaseApp.zza(Unknown Source) 
                                                                               at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                               at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                               at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                               at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source) 
                                                                               at android.content.ContentProvider.attachInfo(ContentProvider.java:1748) 
                                                                               at android.content.ContentProvider.attachInfo(ContentProvider.java:1723) 
                                                                               at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source) 
                                                                               at android.app.ActivityThread.installProvider(ActivityThread.java:5153) 
                                                                               at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748) 
                                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688) 
                                                                               at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:148) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
09-04 11:29:37.557 13353-13353/org.radarcns.android.android I/FirebaseInitProvider: FirebaseApp initialization successful
09-04 11:29:37.639 13353-13353/org.radarcns.android.android W/GooglePlayServicesUtil: Google Play Store is missing.
09-04 11:29:37.646 13353-13353/org.radarcns.android.android I/o*.r*.a*.MainActivity: RADAR configuration at create: RadarConfiguration:
09-04 11:29:37.751 13353-13353/org.radarcns.android.android I/o*.r*.DeviceRowView: Creating device row for provider PhoneSensorProvider<PhoneSensorService> and connection DeviceServiceConnection<org.radarcns.phone.PhoneSensorService>
09-04 11:29:37.773 13353-13353/org.radarcns.android.android I/o*.r*.DeviceRowView: device filter did not change - ignoring
09-04 11:29:37.776 13353-13353/org.radarcns.android.android I/o*.r*.DeviceRowView: Creating device row for provider E4ServiceProvider<E4Service> and connection DeviceServiceConnection<org.radarcns.empatica.E4Service>
09-04 11:29:37.797 13353-13353/org.radarcns.android.android I/o*.r*.DeviceRowView: device filter did not change - ignoring
09-04 11:29:37.809 13353-13353/org.radarcns.android.android I/o*.r*.a*.MainActivity: mainActivity onStart
09-04 11:29:37.818 13353-13353/org.radarcns.android.android I/o*.r*.a*.MainActivity: mainActivity onResume
09-04 11:29:37.830 13353-13458/org.radarcns.android.android D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
09-04 11:29:37.834 13353-13353/org.radarcns.android.android I/imx6.gralloc: open gpu gralloc module!
09-04 11:29:37.858 13353-13457/org.radarcns.android.android I/o*.r*.a*.MainActivity: Binding to service: ApplicationServiceProvider<ApplicationStatusService>
09-04 11:29:37.859 13353-13457/org.radarcns.android.android I/DeviceServiceProvider: Binding ApplicationServiceProvider<ApplicationStatusService>
09-04 11:29:37.901 13353-13353/org.radarcns.android.android I/o*.r*.DeviceRowView: Device status is DISCONNECTED
09-04 11:29:37.902 13353-13353/org.radarcns.android.android I/o*.r*.DeviceRowView: Device status is DISCONNECTED
09-04 11:29:37.946 13353-13457/org.radarcns.android.android I/o*.r*.a*.MainActivity: Binding to service: PhoneSensorProvider<PhoneSensorService>
09-04 11:29:37.977 13353-13457/org.radarcns.android.android I/DeviceServiceProvider: Binding PhoneSensorProvider<PhoneSensorService>
09-04 11:29:37.991 13353-13457/org.radarcns.android.android I/o*.r*.a*.MainActivity: Binding to service: E4ServiceProvider<E4Service>
09-04 11:29:37.991 13353-13457/org.radarcns.android.android I/DeviceServiceProvider: Binding E4ServiceProvider<E4Service>
09-04 11:29:38.015 13353-13458/org.radarcns.android.android I/OpenGLRenderer: Initialized EGL, version 1.4
09-04 11:29:38.041 152-1684/? E/BufferQueueProducer: [org.radarcns.android.android/org.radarcns.DetailMainActivity] dequeueBuffer: can't dequeue multiple buffers without setting the buffer count
09-04 11:29:38.069 13353-13353/org.radarcns.android.android I/DeviceService: Creating DeviceService org.radarcns.application.ApplicationStatusService@aea50dd
09-04 11:29:38.072 13353-13353/org.radarcns.android.android I/DeviceService: Starting DeviceService org.radarcns.application.ApplicationStatusService@aea50dd
09-04 11:29:38.293 13353-13353/org.radarcns.android.android W/Java7Support: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
09-04 11:29:38.695 13353-13353/org.radarcns.android.android I/Choreographer: Skipped 47 frames!  The application may be doing too much work on its main thread.
09-04 11:29:38.907 13353-13353/org.radarcns.android.android I/DeviceService: Received (re)bind in org.radarcns.application.ApplicationStatusService@aea50dd
09-04 11:29:38.917 1060-1078/? I/ActivityManager: Displayed org.radarcns.android.android/org.radarcns.DetailMainActivity: +4s752ms
09-04 11:29:38.923 13353-13353/org.radarcns.android.android I/DeviceService: Creating DeviceService org.radarcns.phone.PhoneSensorService@bbcaae1
09-04 11:29:38.928 13353-13353/org.radarcns.android.android I/DeviceService: Starting DeviceService org.radarcns.phone.PhoneSensorService@bbcaae1
09-04 11:29:38.965 13353-13353/org.radarcns.android.android I/DeviceService: Received (re)bind in org.radarcns.phone.PhoneSensorService@bbcaae1
09-04 11:29:38.974 13353-13353/org.radarcns.android.android I/DeviceService: Creating DeviceService org.radarcns.empatica.E4Service@ba6a9d5
09-04 11:29:38.982 13353-13353/org.radarcns.android.android I/DeviceService: Starting DeviceService org.radarcns.empatica.E4Service@ba6a9d5
09-04 11:29:39.054 13353-13353/org.radarcns.android.android I/o*.r*.e*.E4Service: Using API key a48af4c20b7644cc869fa806a13871a3
09-04 11:29:39.073 13353-13353/org.radarcns.android.android I/DeviceService: Received (re)bind in org.radarcns.empatica.E4Service@ba6a9d5
09-04 11:29:39.168 13353-13353/org.radarcns.android.android I/BaseServiceConnection: Bound to service ComponentInfo{org.radarcns.android.android/org.radarcns.application.ApplicationStatusService}
09-04 11:29:39.169 13353-13353/org.radarcns.android.android I/o*.r*.a*.MainActivity: Initial server status: READY
09-04 11:29:39.169 13353-13353/org.radarcns.android.android I/o*.r*.a*.MainActivity: Starting recording on connection DeviceServiceConnection<org.radarcns.application.ApplicationStatusService>
09-04 11:29:39.169 13353-13353/org.radarcns.android.android I/DeviceService: Starting recording
09-04 11:29:39.184 13353-13353/org.radarcns.android.android I/*plicationStatusManager: Starting ApplicationStatusManager
09-04 11:29:39.188 13353-13353/org.radarcns.android.android I/*plicationStatusManager: App status updater: listener activated and set to a period of 20
09-04 11:29:39.197 13353-13464/org.radarcns.android.android I/*plicationStatusManager: Updating application status
09-04 11:29:39.210 13353-13464/org.radarcns.android.android I/*plicationStatusManager: Server Status: DISCONNECTED; Device IP: null
09-04 11:29:39.232 13353-13353/org.radarcns.android.android I/BaseServiceConnection: Bound to service ComponentInfo{org.radarcns.android.android/org.radarcns.phone.PhoneSensorService}
09-04 11:29:39.232 13353-13353/org.radarcns.android.android I/o*.r*.a*.MainActivity: Initial server status: READY
09-04 11:29:39.233 13353-13353/org.radarcns.android.android I/o*.r*.a*.MainActivity: Starting recording on connection DeviceServiceConnection<org.radarcns.phone.PhoneSensorService>
09-04 11:29:39.233 13353-13353/org.radarcns.android.android I/DeviceService: Starting recording
09-04 11:29:39.234 13353-13464/org.radarcns.android.android I/*plicationStatusManager: Number of records: {sent: 0, unsent: 0, cached: 0}
09-04 11:29:39.242 13353-13353/org.radarcns.android.android W/PhoneSensorManager: Phone Accelerometer not found
09-04 11:29:39.242 13353-13353/org.radarcns.android.android W/PhoneSensorManager: Phone Light sensor not found
09-04 11:29:39.280 13353-13353/org.radarcns.android.android I/BaseServiceConnection: Bound to service ComponentInfo{org.radarcns.android.android/org.radarcns.empatica.E4Service}
09-04 11:29:39.286 13353-13353/org.radarcns.android.android I/o*.r*.a*.MainActivity: Initial server status: READY
09-04 11:29:39.288 1060-1077/? D/BluetoothManagerService: Added callback: android.bluetooth.IBluetoothManagerCallback$Stub$Proxy@4e15e14:true
09-04 11:29:39.290 13353-13353/org.radarcns.android.android I/o*.r*.a*.MainActivity: Starting recording on connection DeviceServiceConnection<org.radarcns.empatica.E4Service>
09-04 11:29:39.290 13353-13353/org.radarcns.android.android I/DeviceService: Starting recording
09-04 11:29:39.298 13353-13353/org.radarcns.android.android I/E4DeviceManager: Starting scanning
09-04 11:29:39.305 13353-13465/org.radarcns.android.android I/E4DeviceManager: Creating EmpaDeviceManager
09-04 11:29:39.308 13353-13353/org.radarcns.android.android I/DeviceServiceConnection: Device status changed of device org.radarcns.android.android
09-04 11:29:39.308 13353-13353/org.radarcns.android.android I/DeviceServiceConnection: Updated device status to CONNECTED
09-04 11:29:39.324 13353-13465/org.radarcns.android.android E/EMPA_C: Loaded
09-04 11:29:39.353 13353-13353/org.radarcns.android.android I/DeviceServiceConnection: Device status changed of device UDOONEO-MX6SX
09-04 11:29:39.353 13353-13353/org.radarcns.android.android I/DeviceServiceConnection: Updated device status to CONNECTED
09-04 11:29:39.369 1060-1670/? I/NotificationService: cancelToast pkg=org.radarcns.android.android callback=android.app.ITransientNotification$Stub$Proxy@61756bd
09-04 11:29:39.447 13353-13465/org.radarcns.android.android I/E4DeviceManager: Updated E4 status to DISCONNECTED
09-04 11:29:39.470 13353-13465/org.radarcns.android.android I/E4DeviceManager: Authenticating EmpaDeviceManager
09-04 11:29:39.490 13353-13364/org.radarcns.android.android W/art: Suspending all threads took: 17.831ms
09-04 11:29:39.500 13353-13465/org.radarcns.android.android I/E4DeviceManager: Authenticated EmpaDeviceManager
09-04 11:29:39.518 13353-13364/org.radarcns.android.android I/art: Background partial concurrent mark sweep GC freed 13357(930KB) AllocSpace objects, 2(40KB) LOS objects, 40% free, 3MB/6MB, paused 21.580ms total 172.310ms
09-04 11:29:39.524 152-900/? E/BufferQueueProducer: [Toast] dequeueBuffer: can't dequeue multiple buffers without setting the buffer count
09-04 11:29:39.688 13353-13353/org.radarcns.android.android I/o*.r*.DeviceRowView: Device status is CONNECTED
09-04 11:29:39.805 13353-13467/org.radarcns.android.android E/DeviceLabelHandler: Error downloading label file
09-04 11:29:39.931 13353-13353/org.radarcns.android.android D/AndroidRuntime: Shutting down VM
09-04 11:29:39.933 13353-13353/org.radarcns.android.android E/E4DeviceManager: Empatica crashed because there is no internet connection. Disconnecting
                                                                               com.empatica.empalink.ConfigurationProfileException: Login failed and you don't have a valid local configuration profile
                                                                                   at com.empatica.empalink.EmpaDeviceManager.b(EmpaDeviceManager.java:843)
                                                                                   at com.empatica.empalink.EmpaDeviceManager.a(EmpaDeviceManager.java:67)
                                                                                   at com.empatica.empalink.EmpaDeviceManager$b.a(EmpaDeviceManager.java:1005)
                                                                                   at com.empatica.empalink.EmpaDeviceManager$b.onPostExecute(EmpaDeviceManager.java:978)
                                                                                   at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                                   at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                                   at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-04 11:29:39.938 1060-1171/? I/NotificationService: cancelToast pkg=org.radarcns.android.android callback=android.app.ITransientNotification$Stub$Proxy@86f8698
09-04 11:29:39.948 13353-13353/? I/E4DeviceManager: Closing device UDOONEO-MX6SX
09-04 11:29:39.950 13353-13465/? I/E4DeviceManager: Initiated device UDOONEO-MX6SX stop-sequence
09-04 11:29:39.951 13353-13465/? I/E4DeviceManager: Updated E4 status to DISCONNECTED
09-04 11:29:39.951 13353-13465/? I/E4DeviceManager: Cleaning up device manager
09-04 11:29:39.953 13353-13465/? I/E4DeviceManager: Cleaned up device manager
09-04 11:29:39.953 13353-13465/? I/E4DeviceManager: Finished device UDOONEO-MX6SX stop-sequence
09-04 11:29:39.971 13353-13364/? I/art: Starting a blocking GC HeapTrim
09-04 11:29:39.986 13353-13360/? I/art: Debugger is no longer active
09-04 11:29:41.181 13469-13469/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
09-04 11:29:41.189 13469-13469/? D/AndroidRuntime: CheckJNI is OFF
09-04 11:29:41.189 13469-13469/? E/cutils-trace: Error opening trace file: No such file or directory (2)
09-04 11:29:41.265 13469-13469/? D/ICU: No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
09-04 11:29:41.340 13469-13469/? E/memtrack: Couldn't load memtrack module (No such file or directory)
09-04 11:29:41.341 13469-13469/? E/android.os.Debug: failed to load memtrack module: -2
09-04 11:29:41.354 13469-13469/? I/Radio-JNI: register_android_hardware_Radio DONE
09-04 11:29:41.412 13469-13469/? D/AndroidRuntime: Calling main entry com.android.commands.am.Am
09-04 11:29:41.415 1060-1071/? I/ActivityManager: Force stopping org.radarcns.android.android appid=10052 user=0: from pid 13469
09-04 11:29:41.416 1060-1071/? I/ActivityManager: Killing 13353:org.radarcns.android.android/u0a52 (adj 1): stop org.radarcns.android.android
09-04 11:29:41.489 1060-2201/? I/WindowState: WIN DEATH: Window{67a1b9 u0 Toast}
09-04 11:29:41.497 1060-3008/? D/GraphicsStats: Buffer count: 4
09-04 11:29:41.512 1060-3008/? I/WindowState: WIN DEATH: Window{a2b6cb u0 org.radarcns.android.android/org.radarcns.DetailMainActivity}
09-04 11:29:41.525 1060-1071/? D/ActivityManager: cleanUpApplicationRecord -- 13353
09-04 11:29:41.532 1060-1071/? W/ActivityManager: Scheduling restart of crashed service org.radarcns.android.android/org.radarcns.phone.PhoneSensorService in 1000ms
09-04 11:29:41.534 1060-1071/? W/ActivityManager: Scheduling restart of crashed service org.radarcns.android.android/org.radarcns.application.ApplicationStatusService in 10999ms
09-04 11:29:41.535 1060-1071/? W/ActivityManager: Scheduling restart of crashed service org.radarcns.android.android/org.radarcns.empatica.E4Service in 20998ms
09-04 11:29:41.536 1060-1071/? W/ActivityManager: Force removing ActivityRecord{f750371 u0 org.radarcns.android.android/org.radarcns.DetailMainActivity t450}: app died, no saved state
09-04 11:29:41.565 1060-1071/? I/ActivityManager:   Force stopping service ServiceRecord{ca3f4a7 u0 org.radarcns.android.android/org.radarcns.phone.PhoneSensorService}
09-04 11:29:41.565 1060-1071/? I/ActivityManager:   Force stopping service ServiceRecord{425c5f2 u0 org.radarcns.android.android/org.radarcns.empatica.E4Service}
09-04 11:29:41.565 1060-1071/? I/ActivityManager:   Force stopping service ServiceRecord{c26b245 u0 org.radarcns.android.android/org.radarcns.application.ApplicationStatusService}
09-04 11:29:41.568 1060-1171/? W/ActivityManager: Spurious death for ProcessRecord{4fbdea8 0:org.radarcns.android.android/u0a52}, curProc for 13353: null
09-04 11:29:41.570 1060-1078/? W/WindowAnimator: Failed to dispatch window animation state change.
                                                 android.os.DeadObjectException
                                                     at android.os.BinderProxy.transactNative(Native Method)
                                                     at android.os.BinderProxy.transact(Binder.java:503)
                                                     at android.view.IWindow$Stub$Proxy.onAnimationStarted(IWindow.java:520)
                                                     at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:282)
                                                     at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
                                                     at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
                                                     at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                     at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                     at com.android.server.ServiceThread.run(ServiceThread.java:46)
09-04 11:29:41.584 13469-13469/? D/AndroidRuntime: Shutting down VM
09-04 11:29:41.625 152-900/? E/BufferQueueProducer: [com.android.launcher/com.android.launcher2.Launcher] dequeueBuffer: can't dequeue multiple buffers without setting the buffer count
09-04 11:29:41.647 1060-1638/? W/InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 13353 uid 10052
09-04 11:29:42.078 1060-1078/? W/WindowAnimator: Failed to dispatch window animation state change.
                                                 android.os.DeadObjectException
                                                     at android.os.BinderProxy.transactNative(Native Method)
                                                     at android.os.BinderProxy.transact(Binder.java:503)
                                                     at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
                                                     at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
                                                     at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
                                                     at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
                                                     at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                     at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                     at com.android.server.ServiceThread.run(ServiceThread.java:46)
09-04 11:29:42.161 1572-1678/? W/OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
09-04 11:29:43.450 1060-1060/? W/NotificationService: Object died trying to hide notification android.app.ITransientNotification$Stub$Proxy@cc1bad6 in package org.radarcns.android.android
</code></pre>
</details>
</br>

Is `E/DeviceLabelHandler: Error downloading label file` an Empatica thing? I could not find it in the RADAR code, and it is not Android.
Also why is the device called like this `I/E4DeviceManager: Closing device UDOONEO-MX6SX`? Is it just a stand-in until an actual E4 is connected?

Edit: I also tried updating the status to `READY` instead of `DISCONNECTED`, with the same end result.

**Pull request closed without merging**
